apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: basic
spec:
  # Use role name here
  role: "${node_iam_role_name}"
  subnetSelectorTerms:
    - tags:
        Name: "${subnet_prefix}"
  securityGroupSelectorTerms:
    - tags:
        Name: "${sg_name}"
  ephemeralStorage:
    size: "80Gi"    # Range: 1-9000Gi or 1-64000G or 1-58Ti or 1-64T
    iops: 3000      # Range: 3000-16000
    throughput: 125 # Range: 125-1000
